### ISSUE TITLE
Spaces/comments in type declarations

### ISSUE THREAD

**Issue by Romain360** [toroidal-code/language-ocaml#7]
The following code in an .mli file will break highlighting:

(*\* Lists *)
type my_list =
  | Nil
  | Cons of expr \* my_list

(*\* Expressions *)
and expr =
  | Int of int
  | List of my_list

Looking at the regular expression used for highlighting, this is because correct highlighting requires the entire code to be recognized as a single type declaration block but whitespaces and comments are not allowed in such blocks. Unfortunately I don't see an easy fix for this.

![screenshot001](https://cloud.githubusercontent.com/assets/1814670/7786139/801121b6-01b8-11e5-8c5a-525950bff6f1.jpg)

**Comment by Giltho** [comment]
Anyone has any clue one how to fix this ?

**Comment by rameshvarun** [comment]
This specific issue was fixed in f2980afd6a30adf154bc6ee702bb7b97d678cff3 and can be closed.

<img width="298" alt="screen shot 2017-07-26 at 8 01 01 pm" src="https://user-images.githubusercontent.com/889879/28652515-35d11be0-723d-11e7-93ab-09af32b4cd03.png">

However, an empty line within a type definition still messes up highlighting, which is fixed in #47

**Comment by Giltho** [comment]
Thank you rameshvarun !!
